# Generated by Django 4.2.6 on 2023-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('ten_th_marks', models.CharField(max_length=50)),
                ('twelt_th_marks', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student_details',
                'ordering': ('id',),
            },
        ),
    ]
